#!/usr/bin/env sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell available, you may
#       specify it by setting the SHELL variable when running this script.
#       Example: SHELL=/bin/bash ./gradlew <taskname>
#       SHELL=/bin/ksh ./gradlew <taskname>
#       etc.
#
#   (2) The calling process (cron, errand, etc.) must set the fields in the
#       environment variables so that the defaults below are not used.
#
##############################################################################

# if it's in an array, use the last element
if [ "${1: -4}" = ".jar" ]; then
    mydir="$( cd "$( dirname "$0" )" && pwd )"
    exec java -jar "$mydir/$1" "${@:2}"
fi

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path="$0"

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in
    /*) app_path=$link ;;
    *) app_path=$APP_HOME$link ;;
    esac
done

APP_HOME=$( cd "${APP_HOME}" && pwd -P ) || exit

PROP_FILE="$APP_HOME/gradle.properties"
if [ -e "$PROP_FILE" ]; then
   while IFS="=" read -r k v
   do
      case $k in
      *export*)  eval export "${k%export }" \"${v}\" ;;
      *)         if [ "${k}" = import ]; then
                   . "${v}"
                 else
                   export "${k}"="${v}"
                 fi ;;
      esac
   done < "$PROP_FILE"
fi

# Add default JVM options here. You can use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='" -Xmx64m" "-Xms64m"'

JAVA_OPTS="${JAVA_OPTS:-$DEFAULT_JVM_OPTS}"
JAVA_OPTS="$JAVA_OPTS"

# Collect all arguments for the java command;
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#   * shell script including quotes and variable substitutions, so put them in
#   * double quotes to make sure that "$var" expands to its value, not the
#   * name of the variable itself.

set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

exec "$JAVACMD" "$@"
